use("bookingDB");
db.movies.insertMany([
  {
    title: "The Conjuring: Last Rites",
    posterImage: "https://image.tmdb.org/t/p/w780/7JzOmJ1fIU43I3gLHYsY8UzNzjG.jpg",
    description: "Paranormal investigators Ed and Lorraine Warren take on one last terrifying case involving mysterious entities they must confront.",
    price: 14.99,
    releaseYear: 2025,
    category: "horror",
  },
  {
    title: "The Lost Princess",
    posterImage: "https://image.tmdb.org/t/p/w780/31S2ISsDtbnxb0kuXZl1SxSMD0K.jpg",
    description: "After an Ayahuasca vision transports him to a haunted castle, Alec meets Hanna who tales him the story of her mother's forced marriage and how the forbidden passion with her father was in danger when the princess pregnancy became obvious",
    price: 13.99,
    releaseYear: 2025,
    category: "action",
  },
  {
    title: "Demon Slayer: Kimetsu no Yaiba Infinity Castle",
    posterImage: "https://image.tmdb.org/t/p/w780/sUsVimPdA1l162FvdBIlmKBlWHx.jpg",
    description: "The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.",
    price: 15.99,
    releaseYear: 2025,
    category: "animation",
  },
  {
    title: "War of the Worlds",
    posterImage: "https://image.tmdb.org/t/p/w780/yvirUYrva23IudARHn3mMGVxWqM.jpg",
    description: "Will Radford is a top analyst for Homeland Security who tracks potential threats through a mass surveillance program, until one day an attack by an unknown entity leads him to question whether the government is hiding something from him... and from the rest of the world.",
    price: 12.99,
    releaseYear: 2025,
    category: "sci-fi",
  },
  {
    title: "The Toxic Avenger Unrated",
    posterImage: "https://image.tmdb.org/t/p/w780/sIonGSpGNtH72OzbJllPOEMNjVU.jpg",
    description: "When a downtrodden janitor, Winston Gooze (Peter Dinklage), is exposed to a catastrophic toxic accident, he’s transformed into a new kind of hero: The Toxic Avenger.",
    price: 11.99,
    releaseYear: 2025,
    category: "action",
  },
  {
    title: "Marco",
    posterImage: "https://image.tmdb.org/t/p/w780/il3ao5gcF6fZNqo1o9o7lusmEyU.jpg",
    description: "Marco sets off on a ruthless quest for vengeance after his brother is brutally murdered, finding only betrayal, loss and unimaginable brutality at every step.",
    price: 10.99,
    releaseYear: 2024,
    category: "thriller",
  },
  {
    title: "Holy Night: Demon Hunters",
    posterImage: "https://image.tmdb.org/t/p/w780/v3Mo77Qjp6pctpD4eJaNT6kFRSB.jpg",
    description: "When a devil-worshipping criminal network plunges Seoul into chaos, the police turn to Holy Night—a trio of supernatural demon hunters—to restore order and defeat the rising evil.",
    price: 12.99,
    releaseYear: 2025,
    category: "horror",
  },
  {
    title: "War 2",
    posterImage: "https://image.tmdb.org/t/p/w780/tHUEGjexjpTDO3ggla9JQ6CojxU.jpg",
    description: "Agent Kabir went rogue, and India sends its deadliest agent Vikram to stop him.",
    price: 13.49,
    releaseYear: 2025,
    category: "action",
  },
  {
    title: "Our Fault",
    posterImage: "https://image.tmdb.org/t/p/w780/yzqHt4m1SeY9FbPrfZ0C2Hi9x1s.jpg",
    description: "Jenna and Lion's wedding brings about the reunion between Noah and Nick after their breakup. Will love be stronger than resentment?",
    price: 9.99,
    releaseYear: 2025,
    category: "romance",
  },
  {
    title: "The Fantastic 4: First Steps",
    posterImage: "https://image.tmdb.org/t/p/w780/cm8TNGBGG0aBfWj0LgrESHv8tir.jpg",
    description: "Marvel's First Family must defend Earth from Galactus while balancing their family bond.",
    price: 16.99,
    releaseYear: 2025,
    category: "sci-fi",
  },
  {
    title: "Inside Furioza",
    posterImage: "https://image.tmdb.org/t/p/w780/yOLnV1lM3NuMsgYwIhz454fQRgt.jpg",
    description: "After murder strikes, Golden takes control of the violent Furioza gang and expands their operations.",
    price: 10.99,
    releaseYear: 2025,
    category: "action",
  },
  {
    title: "Play Dirty",
    posterImage: "https://image.tmdb.org/t/p/w780/ovZ0zq0NwRghtWI1oLaM0lWuoEw.jpg",
    description: "Expert thief Parker plans a major heist but must outsmart dangerous forces.",
    price: 11.99,
    releaseYear: 2025,
    category: "thriller",
  },
  {
    title: "The Woman in Cabin 10",
    posterImage: "https://image.tmdb.org/t/p/w780/4kpdyePOlcELQQJcxXPF5GB1Adw.jpg",
    description: "A journalist on a luxury yacht sees a passenger go overboard, but no one believes her.",
    price: 12.49,
    releaseYear: 2025,
    category: "thriller",
  },
  {
    title: "Primitive War",
    posterImage: "https://image.tmdb.org/t/p/w780/nWBqU5YXmDVJWWEDJ4u3ZSseNVL.jpg",
    description: "During the Vietnam War, soldiers discover prehistoric dinosaurs in the jungle.",
    price: 14.49,
    releaseYear: 2025,
    category: "action",
  },
  {
    title: "Vicious",
    posterImage: "https://image.tmdb.org/t/p/w780/shKGDGrwqmc9x2aTJcQszoXinq0.jpg",
    description: "Polly receives a mysterious box with dark consequences if its rules are broken.",
    price: 11.49,
    releaseYear: 2025,
    category: "horror",
  },
  {
    title: "TRON: Ares",
    posterImage: "https://image.tmdb.org/t/p/w780/chpWmskl3aKm1aTZqUHRCtviwPy.jpg",
    description: "A program named Ares crosses into the real world, marking humanity's first contact with AI beings.",
    price: 15.99,
    releaseYear: 2025,
    category: "sci-fi",
  },
  {
    title: "HIM",
    posterImage: "https://image.tmdb.org/t/p/w780/qPJzcYR2f1O1uynYBCVPPJuOiAH.jpg",
    description: "A young quarterback trains with his hero, but things take a sinister turn.",
    price: 9.99,
    releaseYear: 2025,
    category: "thriller",
  },
  {
    title: "KPop Demon Hunters",
    posterImage: "https://image.tmdb.org/t/p/w780/AjlRXTpRLAIiuofNqKcqrpUfPCZ.jpg",
    description: "When K-pop idols aren't performing, they're fighting supernatural threats to protect their fans.",
    price: 13.49,
    releaseYear: 2025,
    category: "animation",
  },
  {
    title: "Prisoner of War",
    posterImage: "https://image.tmdb.org/t/p/w780/1XET89sjRm9mUuHXhGIlKTNd5uD.jpg",
    description: "Captured by the Japanese during WWII, a British pilot must fight to survive.",
    price: 10.49,
    releaseYear: 2025,
    category: "thriller",
  },
  {
    title: "Mantis",
    posterImage: "https://image.tmdb.org/t/p/w780/xS9bbciDC5lHPgl79SrPyzxKAXL.jpg",
    description: "An ace assassin returns to the underworld, facing old allies and deadly rivals.",
    price: 12.99,
    releaseYear: 2025,
    category: "action",
  },
]
)